name: ${name}
version: ${version}
description: ${description}
website: ${url}
database: false
depend: [WorldGuard]
softdepend: [BlocksHub,WorldEdit]
author: [Challenger2]
main: nu.nerd.SpeedBuildArena.SBAPlugin
api-version: 1.18

commands:
  speedbuildarena:
    description: Speed Build Arena Commands.
    aliases: [sba, speedbuild]

permissions:
  speedbuildarena.*:
    description: Give access to all Speed Build Arena commands
    default: op
    children:
      speedbuildarena.admin: true
  speedbuildarena.admin:
    default: op
    description: Gives access to start and abort sub-commands
